### ISSUE TITLE
Train and deploy my custom tflite model

### ISSUE THREAD

**Issue by LeonoreShaw** [BoxOfTheFox/CameraX_TF_lite#1]
I wanna deploy my custom model on this app to detect traffic sign. How should I train my custom model and deploy it directly on this app? 
Thank you.

**Comment by BoxOfTheFox** [comment]
This project is based on [this tutorial](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android). I used pretrained model available on [tfhub](https://tfhub.dev/s?module-type=image-object-detection) and then from app I've filtered buses.

To do it correctly you'll have to find or create dataset with traffic signs and then using transfer learning with [TFLite Model Maker ](https://www.tensorflow.org/lite/models/modify/model_maker) train your model. You can find example on how to do it [here](https://www.tensorflow.org/lite/models/modify/model_maker/object_detection).
